AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.debug
      MemorySize: 1024
      Timeout: 15
      Policies: AmazonS3FullAccess
      Runtime: nodejs4.3
      Environment:
        Variables: 
          S3_BUCKET: !Ref WebsiteBucket
