AWSTemplateFormatVersion: "2010-09-09"

Resources:
  CodePipelineRole:
    Type: "AWS::IAM::Role"
    Properties: 
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Action: sts:AssumeRole
          Principal:
            Service: codepipeline.amazonaws.com
          Effect: Allow
          Sid: ""
      Policies:
        - PolicyName: "CodePipeline"
          PolicyDocument: 
            Version: '2012-10-17'
            Statement:
            - Action:
                - s3:GetObject
                - s3:GetObjectVersion
                - s3:GetBucketVersioning
              Resource: "*"
              Effect: Allow
            - Action:
              - s3:PutObject
              Effect: Allow
              Resource: "arn:aws:s3:::codepipeline*"
            - Action:
                - sns:Publish 
              Resource: "*"
              Effect: Allow
            - Action:
                - lambda:InvokeFunction
                - lambda:ListFunctions
              Resource: "*"
              Effect: Allow
            - Action:
                - cloudformation:CreateStack
                - cloudformation:DeleteStack
                - cloudformation:DescribeStacks
                - cloudformation:UpdateStack
                - cloudformation:CreateChangeSet
                - cloudformation:DeleteChangeSet
                - cloudformation:DescribeChangeSet
                - cloudformation:ExecuteChangeSet
                - cloudformation:SetStackPolicy
                - cloudformation:ValidateTemplate
                - iam:PassRole
              Resource: "*"
              Effect: Allow
            - Action:
                - codebuild:BatchGetBuilds
                - codebuild:StartBuild
              Resource: "*"
              Effect: Allow

  CloudFormationRole:
    Type: "AWS::IAM::Role"
    Properties: 
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Action: sts:AssumeRole
          Principal:
            Service: cloudformation.amazonaws.com
          Effect: Allow
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
      Policies:
        - PolicyName: "CloudFormation"
          PolicyDocument: 
            Version: "2012-10-17"
            Statement: 
              - Effect: "Allow"
                Action: 
                  - dynamodb:CreateTable
                  - dynamodb:DescribeTable
                  - dynamodb:DeleteTable
                  - dynamodb:UpdateTable
                Resource: "*"

Outputs:
  CodePipelineRoleArn:
    Description: Arn of the codepipeline role
    Value: !GetAtt CodePipelineRole.Arn
    Export:    
      Name: CodePipelineRoleArn
  CloudFormationRoleArn:
    Description: Arn of the CloudFormation role
    Value: !GetAtt CloudFormationRole.Arn
    Export:    
      Name: CloudFormationRoleArn
