AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  OAuth:
    Description: OAuth Token for Github Access
    Default: "****"
    Type: String
    NoEcho: true

Resources:
  DevOpsTopic:
    Type: "AWS::SNS::Topic"
    Properties: 
      TopicName: "offcourse-infrastructure"
      Subscription:
        - Endpoint: "yeehaa@offcourse.io"
          Protocol: email
  Pipeline:
    Type: "AWS::CodePipeline::Pipeline"
    Properties:
      Name: offcourse-infrastructure
      RoleArn: !ImportValue CodePipelineRoleArn
      Stages:
      - Name: Source
        Actions:
        - Name: Source
          ActionTypeId:
            Category: Source
            Owner: ThirdParty
            Version: '1'
            Provider: GitHub
          OutputArtifacts:
          - Name: Offcourse
          Configuration:
            Owner: OffCourse
            Repo: infrastructure
            Branch: master
            OAuthToken: !Ref OAuth
          RunOrder: 1
      - Name: Dev
        Actions:
        - InputArtifacts:
          - Name: Offcourse
          Name: offcourse-infrastructure-dev
          ActionTypeId:
            Category: Deploy
            Owner: AWS
            Version: '1'
            Provider: CloudFormation
          OutputArtifacts: []
          Configuration:
            StackName: offcourse-infrastructure-dev
            ActionMode: CREATE_UPDATE
            Capabilities: CAPABILITY_IAM
            RoleArn: !ImportValue CloudFormationRoleArn
            TemplateConfiguration: Offcourse::dev-config.json
            TemplatePath: Offcourse::index.yml
          RunOrder: 1
      - Name: Edge
        Actions:
        - InputArtifacts: []
          Name: QA
          ActionTypeId:
            Category: Approval
            Owner: AWS
            Version: '1'
            Provider: Manual
          OutputArtifacts: []
          Configuration:
            NotificationArn: !Ref DevOpsTopic
            CustomData: "Approval or Reject this change after running Exploratory Tests"
          RunOrder: 1
        - InputArtifacts:
          - Name: Offcourse
          Name: offcourse-infrastructure-edge
          ActionTypeId:
            Category: Deploy
            Owner: AWS
            Version: '1'
            Provider: CloudFormation
          OutputArtifacts: []
          Configuration:
            StackName: offcourse-infrastructure-edge
            ActionMode: CREATE_UPDATE
            Capabilities: CAPABILITY_IAM
            RoleArn: !ImportValue CloudFormationRoleArn
            TemplateConfiguration: Offcourse::edge-config.json
            TemplatePath: Offcourse::index.yml
          RunOrder: 2
      ArtifactStore:
        Type: S3
        Location: codepipeline-us-east-1-814057763522

Outputs:
  DevOpsTopicArn:
    Description: Arn of the devops sns topic
    Value: !Ref DevOpsTopic
    Export:    
      Name: DevOpsTopicArn
