AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs4.3
      MemorySize: 1024
      Timeout: 30
      Environment:
        Variables: 
          RawDataBucket: !ImportValue "offcourse-RawDataBucket-dev"
