AWSTemplateFormatVersion: '2010-09-09'
Resources:
  TestFunction:
    Properties:
      CodeUri: s3://offcourse-bootstrap/4c480801d0425dc6f7a475eccad6459e
      Environment:
        Variables:
          S3_BUCKET:
            Ref: WebsiteBucket
      Handler: index.handler
      Runtime: nodejs4.3
    Type: AWS::Serverless::Function
  WebsiteBucket:
    Properties:
      WebsiteConfiguration:
        ErrorDocument: index.html
        IndexDocument: index.html
    Type: AWS::S3::Bucket
Transform: AWS::Serverless-2016-10-31
