AWSTemplateFormatVersion: '2010-09-09'
Resources:
  TestFunction:
    Properties:
      CodeUri: s3://offcourse-bootstrap/f45e5267b472f00fd5a41ee8c984f504
      Environment:
        Variables:
          S3_BUCKET:
            Ref: WebsiteBucket
      Handler: index.handler
      Runtime: nodejs4.3
    Type: AWS::Serverless::Function
  WebsiteBucket:
    Properties:
      WebsiteConfiguration:
        ErrorDocument: index.html
        IndexDocument: index.html
    Type: AWS::S3::Bucket
Transform: AWS::Serverless-2016-10-31
