AWSTemplateFormatVersion: '2010-09-09'
Resources:
  TestFunction:
    Properties:
      CodeUri: s3://offcourse-bootstrap/becef2b38243dafff16d563d309e2926
      Environment:
        Variables:
          RawDataBucket:
            Fn::ImportValue: offcourse-RawDataBucket-dev
      Handler: index.handler
      MemorySize: 1024
      Runtime: nodejs4.3
      Timeout: 30
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
